### ISSUE TITLE
fail to launch new Gearpump on YARN after killing previous applications

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump#1785] opened 2015-12-25 05:51 UTC
![screenshot from 2015-12-25 13 47 41](https://cloud.githubusercontent.com/assets/1191767/12000259/0d9069ee-ab0e-11e5-87e8-4a3df8f8cae0.png)

In the screenshot, I've three killed applications (2 of them has finished successfully). Then I want to launch a new  Gearpump (application_1451018909165_0004) on YARN but that timeouts with

```
manu@manu-IdeaCentre-K410:~/git/gearpump$ output/target/pack/bin/yarnclient launch -package /user/manu/gearpump-2.11-0.7.1-SNAPSHOT.zip -output master.conf
[INFO] [12/25/2015 13:44:48.873] [ClusterConfig$] loading config file application.conf...
[INFO] [12/25/2015 13:44:50.061] [RMProxy] Connecting to ResourceManager at /0.0.0.0:8032
[INFO] [12/25/2015 13:44:50.142] [YarnClient] Starting YarnClient...
[INFO] [12/25/2015 13:44:50.427] [Slf4jLogger] Slf4jLogger started
[INFO] [12/25/2015 13:44:50.516] [Remoting] Starting remoting
[INFO] [12/25/2015 13:44:50.687] [Remoting] Remoting started; listening on addresses :[akka.tcp://launchCluster@127.0.0.1:32842]
[INFO] [12/25/2015 13:44:50.721] [Metrics$] Metrics is enabled...,  true
[INFO] [12/25/2015 13:44:50.727] [LaunchCluster] Starting AM
[INFO] [12/25/2015 13:44:51.002] [YarnClient] Create application, appId: application_1451018909165_0004
[INFO] [12/25/2015 13:44:51.003] [LaunchCluster] Uploading configuration files to remote HDFS(under hdfs://localhost:9000/user/manu/.gearpump_app4/conf/)...
[INFO] [12/25/2015 13:44:51.483] [YarnClient] Submit Application application_1451018909165_0004 to YARN...
[INFO] [12/25/2015 13:44:51.511] [YarnClientImpl] Submitted application application_1451018909165_0004
[INFO] [12/25/2015 13:44:51.511] [LaunchCluster] Waiting application to finish...
..............................

Help: 
-package (required:false, default:)<Please specify the gearpump.zip package path on HDFS. If not specified, we will use default value /user/gearpump/gearpump.zip>
-name (required:false, default:Gearpump)<Application name showed in YARN>
-verbose (required:false, default:false)<print verbose log on console>
-output (required:false, default:)<output path for configuration file>

Exception in thread "main" java.lang.Exception: Launch Application application_1451018909165_0004 timeout...
	at io.gearpump.experiments.yarn.glue.YarnClient.awaitApplication(YarnClient.scala:96)
	at io.gearpump.experiments.yarn.client.LaunchCluster.submit(LaunchCluster.scala:93)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:188)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:25)
	at io.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:25)
	at scala.util.Try$.apply(Try.scala:191)
	at io.gearpump.util.AkkaApp$class.main(AkkaApp.scala:24)
	at io.gearpump.experiments.yarn.client.LaunchCluster$.main(LaunchCluster.scala:153)
	at io.gearpump.experiments.yarn.client.Client$.main(Client.scala:45)
	at io.gearpump.experiments.yarn.client.Client.main(Client.scala)

```

**Comment by clockfly** [comment] 2015-12-25 07:39
Looks like the YARN cannot start the app in time. Have you checked the yarn log?

**Comment by manuzhang** [comment] 2015-12-25 07:50
here's the related log.
```
2015-12-25 13:44:51,490 WARN org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl: The specific max attempts: 0 for application: 4 is invalid, because it is out of the range [1, 2]. Use the global max attempts instead.
2015-12-25 13:44:51,490 INFO org.apache.hadoop.yarn.server.resourcemanager.ClientRMService: Application with id 4 submitted by user manu
2015-12-25 13:44:51,490 INFO org.apache.hadoop.yarn.server.resourcemanager.RMAuditLogger: USER=manu     IP=10.239.12.119        OPERATION=Submit Application Request    TARGET=ClientRMService  RESULT=SUCCESS  APPID=application_1451018909165_0004
2015-12-25 13:44:51,490 INFO org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl: Storing application with id application_1451018909165_0004
2015-12-25 13:44:51,491 INFO org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl: application_1451018909165_0004 State change from NEW to NEW_SAVING
2015-12-25 13:44:51,491 INFO org.apache.hadoop.yarn.server.resourcemanager.recovery.RMStateStore: Storing info for app: application_1451018909165_0004
2015-12-25 13:44:51,491 INFO org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl: application_1451018909165_0004 State change from NEW_SAVING to SUBMITTED
2015-12-25 13:44:51,491 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.ParentQueue: Application added - appId: application_1451018909165_0004 user: manu leaf-queue of parent: root #applications: 3
2015-12-25 13:44:51,491 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler: Accepted application application_1451018909165_0004 from user: manu, in queue: default
2015-12-25 13:44:51,491 INFO org.apache.hadoop.yarn.server.resourcemanager.rmapp.RMAppImpl: application_1451018909165_0004 State change from SUBMITTED to ACCEPTED
2015-12-25 13:44:51,492 INFO org.apache.hadoop.yarn.server.resourcemanager.ApplicationMasterService: Registering app attempt : appattempt_1451018909165_0004_000001
2015-12-25 13:44:51,492 INFO org.apache.hadoop.yarn.server.resourcemanager.rmapp.attempt.RMAppAttemptImpl: appattempt_1451018909165_0004_000001 State change from NEW to SUBMITTED
2015-12-25 13:44:51,492 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.LeafQueue: Application added - appId: application_1451018909165_0004 user: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.LeafQueue$User@139f5003, leaf-queue: default #user-pending-applications: 1 #user-active-applications: 2 #queue-pending-applications: 1 #queue-active-applications: 2
2015-12-25 13:44:51,492 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler: Added Application Attempt appattempt_1451018909165_0004_000001 to scheduler from user manu in queue default
2015-12-25 13:44:51,492 INFO org.apache.hadoop.yarn.server.resourcemanager.rmapp.attempt.RMAppAttemptImpl: appattempt_1451018909165_0004_000001 State change from SUBMITTED to SCHEDULED
2015-12-25 13:44:52,323 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler: Null container completed...
2015-12-25 13:44:52,323 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler: Null container completed...
2015-12-25 13:44:52,323 INFO org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler: Null container completed...
...
```

**Comment by clockfly** [comment] 2015-12-25 08:47
Can you grab the yarn app log?

**Comment by clockfly** [comment] 2015-12-25 10:31
The root cause is YarnAppmaster process is not terminated when we kill the gearpump cluster.

**Comment by clockfly** [comment] 2015-12-25 10:31
fixed in https://github.com/gearpump/gearpump/pull/1791

**Closed** 2015-12-25 12:26 UTC
Labels: k: bug
