### ISSUE TITLE
No general way to start, stop Tasks within the DAG lifecycle

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1389] opened 2015-08-31 19:04 UTC
[Story](https://www.pivotaltracker.com/story/show/102403538)

**Comment by clockfly** [comment] 2015-09-12 13:13
Do you mean inifite stream? 

Make this a duplicate of https://github.com/gearpump/gearpump/issues/1230

**Closed by clockfly** 2015-09-12 13:13 UTC
Labels: feature
