### ISSUE TITLE
State example cannot be submitted

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1433] opened 2015-09-16 16:22 UTC
[Story](https://www.pivotaltracker.com/story/show/103517180)
State example fails to submit. No details are provided as to why

**Comment by clockfly** [comment] 2015-09-16 23:46
duplicate of #1423

**Comment by stanleyxu2005** [comment] 2015-09-17 13:46
Now you can see the error message, when uploaded jar is rejected by the server. #1435

**Closed by stanleyxu2005** 2015-09-17 13:46 UTC
Labels: feature
