### ISSUE TITLE
Back pressure flow control is fixed

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#296] opened 2015-01-13 18:30 UTC
This is a prerequisite to #167. The following field is fixed FlowControl.FLOW_CONTROL_RATE = 100. This means that an AckRequest downstream will always be sent every 100 messages by the Publisher. The downstream Subscriber must then return an Ack. This implicit flow control does not allow the Subscriber to control back pressure when needed. The Subscriber should be able to control back pressure through a Subscription class where Subscription.request(demand: Long) is exposed.

**Comment by kkasravi** [comment] 2015-01-13 18:53
This also indirectly applies to #214.

**Comment by kkasravi** [comment] 2015-01-14 02:25
Additional note - for current implementation the publisher has the same FLOW_CONTROL_RATE for all downstream subscribers. The fix should allow the publisher to adjust flow control per subscriber. It's unclear how complex this will be at the moment.

**Comment by clockfly** [comment] 2015-09-12 13:17
mark this as duplicate of #1318

**Closed by clockfly** 2015-09-12 13:17 UTC
Labels: core, P3
