### ISSUE TITLE
Dashboard breaks on YARN

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#1384] opened 2015-08-29 18:40 UTC
[Story](https://www.pivotaltracker.com/story/show/102311712)
Chrome browser goes into an endless loop, details will be added

**Comment by stanleyxu2005** [comment] 2015-08-30 05:42
Possibly caused by routing redirection.

**Comment by kkasravi** [comment] 2015-08-31 04:44
Yes I believe this is the case. Does not happen on localhost.

**Comment by clockfly** [comment] 2015-09-11 09:19
We cannot reproduce this.

@kkasravi 
Can you give more info?

**Comment by stanleyxu2005** [comment] 2015-09-11 12:01
Does it have a port forwarding? If the dashboard is failed to resolve an ajax, it will retry immediately.

**Comment by clockfly** [comment] 2015-09-14 05:31
Close this as it cannot be reproduced.

**Comment by stanleyxu2005** [comment] 2015-09-14 05:35
This can happen. Still need more information to confirm.

**Comment by kkasravi** [comment] 2015-09-18 17:22
It happens when selecting the ApplicationMaster on the YARN RM page. I believe this is due to the proxy URL.

**Comment by kkasravi** [comment] 2015-09-18 17:24
Note we do not plan on accessing GearPump UI via the YARN proxy - rather through a separate proxy that allows POST, PUT, DELETE etc. We should still attempt to fix this issue though.

**Comment by Renkai** [comment] 2015-12-11 02:58
It still happening in the newest snapshot.
<img width="1440" alt="2015-12-07 16 37 26" src="https://cloud.githubusercontent.com/assets/3381789/11734875/077e3766-9ff6-11e5-9523-047ad61cfdc5.png">

**Comment by clockfly** [comment] 2015-12-11 03:01
Thanks, I will check it today.

**Comment by stanleyxu2005** [comment] 2015-12-11 03:06
@Renkai @clockfly `restapiRoot: location.origin,`, the value is "", we expect it as `/proxy/`application.....`

**Comment by stanleyxu2005** [comment] 2015-12-11 06:30
@Renkai The issue has been fixed. Note that the url you are using can only send HTTP GET to Gearpump. Any operations (e.g. submit job), that require HTTP POST, cannot be done. You need to use `http://your_yarn_server:8099/` to submit jobs.

**Comment by kkasravi** [comment] 2015-12-11 08:24
@stanleyxu2005 @Renkai reference https://issues.apache.org/jira/browse/YARN-2084

**Comment by manuzhang** [comment] 2015-12-25 05:12
![screenshot from 2015-12-25 13 12 59](https://cloud.githubusercontent.com/assets/1191767/12000064/0fbec7b0-ab09-11e5-819d-a77d5721403d.png)

I cannot access the Dashboard after it has been running for a while

**Comment by stanleyxu2005** [comment] 2015-12-25 05:14
@manuzhang Please check the error network traffics, and slo post console error logs, if there are some.

**Comment by clockfly** [comment] 2015-12-25 08:59
Can you grab the YARN container logs?

**Comment by manuzhang** [comment] 2015-12-28 08:14
Not reproducible now. I have run Gearpump on YARN applications against latest trunk for 2 hours. Close this.

**Closed by manuzhang** 2015-12-28 08:14 UTC
Labels: k: bug, m: dashboard
