### ISSUE TITLE
File upload service does not accept form with file fields and non-file fields mixed situation

### ISSUE THREAD

**Issue by stanleyxu2005** [gearpump/gearpump#2009] opened 2016-03-18 09:09 UTC
when submit an application, if the request payload looks like this
```
------WebKitFormBoundaryouiAqFeBkqaZ9L9j
Content-Disposition: form-data; name="jar"; filename="wordcount-2.11-0.7.7-SNAPSHOT-assembly.jar"
Content-Type: application/x-java-archive

------WebKitFormBoundaryouiAqFeBkqaZ9L9j
Content-Disposition: form-data; name="conf"; filename="app.conf"
Content-Type: application/octet-stream

------WebKitFormBoundaryouiAqFeBkqaZ9L9j
Content-Disposition: form-data; name="args"

-foo bar
------WebKitFormBoundaryouiAqFeBkqaZ9L9j--
```

The file upload service (in concrete `FileDirective.scala`) will say
```
akka.http.scaladsl.model.ParsingException: Unexpected end of multipart entity
	at akka.http.scaladsl.unmarshalling.MultipartUnmarshallers$$anonfun$multipartUnmarshaller$1$$anonfun$apply$1$$anonfun$1.applyOrElse(MultipartUnmarshallers.scala:94)
	at akka.http.scaladsl.unmarshalling.MultipartUnmarshallers$$anonfun$multipartUnmarshaller$1$$anonfun$apply$1$$anonfun$1.applyOrElse(MultipartUnmarshallers.scala:92)
	at akka.stream.impl.fusing.Collect.onPush(Ops.scala:83)
	at akka.stream.impl.fusing.Collect.onPush(Ops.scala:78)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:436)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:245)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:434)
	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:580)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:241)
	at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:666)
	at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:66)
	at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:157)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:366)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

To simplify the situation, use the following html and to submit a word count application with an empty application file.

```
<!DOCTYPE html>
<html>
<body>
<form id="test1" action="/api/v1.0/master/submitapp" method="POST" enctype="multipart/form-data">
  <table>
    <tr>
      <td>Application (*.jar):</td>
      <td><input type="file" name="jar"/></td>
    </tr>
    <tr>
      <td>Config (*.conf):</td>
      <td><input type="file" name="conf"/></td>
    </tr>
    <tr>
      <td>Arguments:</td>
      <td><input type="text" name="args" value="-foo bar"/></td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Submit"/></td>
    </tr>
  </table>
</form>
</body>
</html>
```

**Comment by kkasravi** [comment] 2016-03-18 09:56
Oh, so this a bug in Upload then?

**Comment by stanleyxu2005** [comment] 2016-03-18 15:02
I believe it's backend issue

**Comment by karol-brejna-i** [comment] 2016-03-21 12:39
I think I may have the way for using config file for my purposes. Let me confirm this with an example.
If this works, the issue is no longer a blocker for me. 

Although I still "feel" that having the args in a form instead of the URL is better.

**Comment by karol-brejna-i** [comment] 2016-03-22 17:45
I am afraid I was overoptimistic. Although there is a way to pass the data as config file, it doesn't apply in this particular case. 
Services credentials are gathered by the console (html5 app) which passes collected data as parameters for the request (there is no way to 'produce' config file to be sent - only valid way is to populate args). 
I am a bit discouraged by @stanleyxu2005 's comment. If I get it right, the stacktrace says the exception is thrown by the "deep" backend (akka.http), not by our code...

**Comment by stanleyxu2005** [comment] 2016-03-23 04:11
From my understanding, while `FileDirective.scala` processes a file upload requests with exception in asynchronous manner, further upload requests will fail. @clockfly what do you think?

**Comment by clockfly** [comment] 2016-03-30 01:45
Fixed by PR 
https://github.com/gearpump/gearpump/pull/2023

**Closed by clockfly** 2016-03-30 01:45 UTC
Labels: k: bug
